# Generated by Django 4.2.25 on 2025-10-30 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marker',
            options={'ordering': ('-created_at',), 'verbose_name': 'Метка', 'verbose_name_plural': 'Метки'},
        ),
        migrations.AlterModelOptions(
            name='markerphoto',
            options={'ordering': ('uploaded_at',), 'verbose_name': 'Фотография метки', 'verbose_name_plural': 'Фотографии меток'},
        ),
        migrations.AlterModelOptions(
            name='pollutiontype',
            options={'ordering': ('name',), 'verbose_name': 'Тип загрязнения', 'verbose_name_plural': 'Типы загрязнений'},
        ),
        migrations.AlterField(
            model_name='marker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='latitude',
            field=models.CharField(max_length=64, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='longitude',
            field=models.CharField(max_length=64, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='pollution_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='markers', to='main_app.pollutiontype', verbose_name='Тип загрязнения'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='region_type',
            field=models.CharField(max_length=100, verbose_name='Тип региона'),
        ),
        migrations.AlterField(
            model_name='markerphoto',
            name='image_path',
            field=models.CharField(max_length=255, verbose_name='Путь к изображению'),
        ),
        migrations.AlterField(
            model_name='markerphoto',
            name='marker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main_app.marker', verbose_name='Метка'),
        ),
        migrations.AlterField(
            model_name='markerphoto',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Загружено'),
        ),
        migrations.AlterField(
            model_name='pollutiontype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='pollutiontype',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Название'),
        ),
    ]
