# Generated by Django 4.2.25 on 2025-10-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_marker_options_alter_markerphoto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='region_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тип региона'),
        ),
    ]
