# Generated by Django 4.2.25 on 2025-10-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_marker_region_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='region_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип региона'),
        ),
    ]
