# Generated by Django 4.2.25 on 2025-10-30 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0004_alter_marker_region_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='markers', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='marker',
            name='creator_username',
            field=models.CharField(blank=True, max_length=150, verbose_name='Имя создателя'),
        ),
    ]
