# Generated by Django 4.2.25 on 2025-10-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_marker_creator_marker_creator_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markerphoto',
            name='image_path',
        ),
        migrations.AddField(
            model_name='markerphoto',
            name='image',
            field=models.ImageField(default='', upload_to='marker_photos/', verbose_name='Изображение'),
        ),
    ]
