# Generated by Django 4.2.25 on 2025-10-30 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0006_remove_markerphoto_image_path_markerphoto_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkerComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marker_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main_app.marker', verbose_name='Метка')),
            ],
            options={
                'verbose_name': 'Комментарий к метке',
                'verbose_name_plural': 'Комментарии к меткам',
                'ordering': ('created_at',),
            },
        ),
    ]
