# Generated by Django 4.2.25 on 2025-10-31 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_markercomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkerStatusStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'В работе'), ('cleared', 'Очищено')], max_length=30, unique=True, verbose_name='Статус')),
                ('count', models.IntegerField(default=0, verbose_name='Количество')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Статистика статусов меток',
                'verbose_name_plural': 'Статистика статусов меток',
            },
        ),
        migrations.CreateModel(
            name='StatusChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название статуса')),
            ],
            options={
                'verbose_name': 'Статус метки',
                'verbose_name_plural': 'Статусы меток',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='marker',
            name='status',
            field=models.CharField(choices=[('in_progress', 'В работе'), ('cleared', 'Очищено')], default='in_progress', max_length=30, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='marker',
            name='status_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='markers', to='main_app.statuschoice', verbose_name='Статус метки'),
        ),
    ]
